apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" . }}-env-secret
  labels:
    {{- include "agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  EMAIL: {{ .Values.configuration.email | quote }}
  PASSWORD: {{ .Values.configuration.password | quote }}
  