apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service-api.fullname" . }}-env-secret
  labels:
    {{- include "service-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.encryption.secretKey | quote }}
  DB_PASSWORD: {{ .Values.postgresql.password | quote }}
  