environments:
  default:
    values:
      - ns: dev
  dev:
    values:
      - ns: dev
  prod:
    values:
      - ns: prod
---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: service-api-postgresql
    chart: bitnami/postgresql
    version: 12.5.4
    installed: true
    namespace: {{.Values.ns}}
    secrets:
      - configuration/service-api-postgresql-secret.yaml
    values:
      - configuration/service-api-postgresql.yaml

  - name: service-api
    chart: service-api
    installed: true
    namespace: {{.Values.ns}}
    needs:
     - {{.Values.ns}}/service-api-postgresql
    secrets:
      - configuration/service-api-secret.yaml
    values:
      - fullnameOverride: service-api
      - postgresql:
          host: service-api-postgresql
